FROM debian:{{ VERSION }} as build
RUN export DEBIAN_FRONTEND=noninteractive; \
    export DEBCONF_NONINTERACTIVE_SEEN=true; \
    apt-get update && apt-get -y upgrade && \
    apt-get install -y build-essential autoconf git zip unzip file libfreetype6-dev \
    libcups2-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev \
    libasound2-dev libffi-dev openjdk-{{ BOOT_JDK_VERSION }}-jdk libfontconfig1-dev clang

WORKDIR /app
RUN git clone https://github.com/openjdk/jdk -b jdk-{{ JDK_VERSION }}
WORKDIR /app/jdk

RUN bash configure --with-debug-level=fastdebug --enable-warnings-as-errors=no \
    --build=x86_64-unknown-linux-gnu --with-toolchain-type=clang
RUN make images
RUN mv build/linux-*/images/jdk /jdk
# Verify that it's working
RUN /jdk/bin/java --version

FROM debian:{{ VERSION }}-slim

COPY --from=build /jdk /jdk

ENV JAVA_HOME="/jdk"
ENV PATH="$PATH:/jdk/bin"

CMD [ "/bin/bash" ]