name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'JDK version to build'
        required: true
      boot-version:
        description: 'Version of the boot jdk to use'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: sudo apt update && sudo apt-get install -y libfreetype6-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libasound2-dev libffi-dev autoconf
      - name: Clone sources
        run: git clone https://github.com/openjdk/jdk -b ${{github.event.inputs.version}}
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: ${{github.event.inputs.boot-version}}
          distribution: 'temurin'
      - name: Configure
        run: bash configure --with-debug-level=fastdebug --enable-asan --enable-warnings-as-errors=no
        working-directory: jdk
      - name: Build
        run: make images JOBS=2
        working-directory: jdk
      - name: Create archive
        run: |
          mkdir out
          mv jdk/build/linux-*/jdk out/jdk
          cd out
          zip -r jdk.zip jdk
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: jdk.zip
